### ISSUE TITLE
Add a date filter to a judgment listing page where a judge has been selected

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1072]
so a user can filter judgments per judge per year
https://new.tanzlii.org/judgments/TZHC/?judges=Kakolaki%2C+J.

**Comment by longhotsummer** [comment]
The current workaround is to choose the year, then apply the judge facet.

**Comment by longhotsummer** [comment]
This is difficult to do well right now. The year navigation doesn't change based on the filters (visually, it comes above the filters to indicate this). If we carry filters over to the year navigation, it means that in many cases the user sees no results because the filters result in no matches. We don't handle that well because we don't show the facets at all, then, because the facets depend on the applied filters.

eg. https://new.tanzlii.org/judgments/TZHC/1994/?registries=High+Court+Arusha+Registry&judges=Aboud%2C+J. looks like this:

![image](https://github.com/laws-africa/peachjam/assets/4178542/37713c7e-13c4-43a2-a682-ed004e17e5a0)

which is a bad user experience.
