### ISSUE TITLE
Footnotes on an uploaded generic document are improperly formatted

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1261]
The footnotes in this document are not appearing correctly:
https://seylii.org/akn/sc/doc/academic-papers/2015-07-31/legal-metissage-in-a-micro-jurisdiction-the-mixing-of-common-law-and-civil-law-in-seychelles/eng@2015-07-31#H3_4242

**Comment by longhotsummer** [comment]
@niiroobiro pls add a screenshot. Please can you also determine what the original source document is. The site shows only a PDF, but the text looks like it comes from a Word document.

**Comment by niiroobiro** [comment]
Here is a screenshot of how the footnotes are appearing after the document is uploaded:

![Image](https://github.com/laws-africa/peachjam/assets/57619722/72a4864f-2e4c-4dc5-9611-5d8ebd52a989)

The document was sent as a pdf document and a Word document. I am not sure which one was used when doing the upload.


[Phd final September 2015  (2).pdf](https://github.com/laws-africa/peachjam/files/11770854/Phd.final.September.2015.2.pdf)



[Phd final September 2015 (2).docx](https://github.com/laws-africa/peachjam/files/11770858/Phd.final.September.2015.2.docx)

**Comment by longhotsummer** [comment]
The cause here is that OpenOffice (soffice) sees these footnote numbers as all zero. By opening it in openoffice, getting it to re-number the footnotes, *and* saving it in openoffice format, the problem is resolved.

https://github.com/laws-africa/peachjam/pull/1387 adds support for importing from the new open-office document.
