### ISSUE TITLE
Taxonomy listing page does not show articles.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1943]
https://zambialii.org/admin/peachjam/article/4/change/

**Comment by niiroobiro** [comment]
Is there a way to add them?

**Comment by actlikewill** [comment]
@longhotsummer The problem here is that users can tag articles with topics, and they expect to see them when they access the taxonomy listing page. In this case, the user created some tags for bill alerts just for articles but they dont see their articles in that list. Maybe we need to have a distinction between tags for coredocuments and tags for articles under a separate branch, and have a listing page just for those, or include articles in the taxonomy listing pages

**Comment by longhotsummer** [comment]
We've simplified this so admins can only tag articles with the article taxonomies.

We currently don't have plans to blend the articles and the other documents on the site.
