### ISSUE TITLE
Show law report citations below document title in search results.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1961]
eg. https://lawlibrary.org.za/akn/za/judgment/zacc/2021/50/eng@2021-12-30 has additional citations in the `alternative_names` field.

![Image](https://github.com/user-attachments/assets/7b094b9d-d73f-44a2-873c-09b42dd5b951)

**Comment by longhotsummer** [comment]
Note that  we already search this field, we just don't show it in the results.

Proposed changes:

* in search results, put the alternative names (an array) as a semi-colon separate list, just beneath the place where we put the citation
* highlight the alternative_names field (see `peachjam_search.views.DocumentSearchViewSet.highlight_fields`) and use that if it has highlights (like we do for the title field)
* (small fix): use `nature` rather than `doc_type` in the search result item detail
