### ISSUE TITLE
Unified UI  for document display

### ISSUE THREAD

**Issue by musangowope** [laws-africa/peachjam#200]
In our current html syntax that handles rendering a document, different html is rendered depending on what document type is present (`akn, html or pdf`). This results in visual lack of consistency between the `akn`, `html`  and `pdf` documents.
PDF Document View:
<img width="1432" alt="pdf-document-view" src="https://user-images.githubusercontent.com/15995210/175273998-59ae288b-f9a5-4185-a9e9-e95205dd37fa.png">

AKN Document:
<img width="1436" alt="akn-document-view" src="https://user-images.githubusercontent.com/15995210/175274099-c4772a22-a315-44dd-b9c1-256eb8a05d06.png">

HTML Document: 
<img width="1439" alt="html-document" src="https://user-images.githubusercontent.com/15995210/175274171-312fe0cb-9467-4827-a37e-4fb304d6a610.png">

**Proposal:**
- First and foremost create a three-column grid UI for which akn, html and pdf document views use:
- - PDF View: left column: (Tabbed content: Page previews, and search),  centre column: pdf, right column: empty
- - AKN View: Left column: (Tabbed content: TOC, and search),  centre column: akn document, right column: la-gutter
- - HTML View: Left column: Search, centre column: html document, right-column empty

- Visibility of left and right columns :
- - Left column should be toggleable in terms of visibility. For the desktop view. We will have cta button that will toggle visibility. On  mobile view it will be the same except, Left column will be overlayed above the centre column on the left (Like a side drawer). So we don't squish the content in mobile view  
- - Right column will be visible in desktop but hidden on mobile, (until start using the la-gutter properly with enrichments)

**Things to consider:**
- Thought needs to go into the color alignment used. i.e what background greys are we using
- PDF pages are canvas elements with text layers overlaid on top of it. So the width of those pages must remain the same size, otherwise, text placement will not be correct if resized. Currently, on mobile view, the page is the same size, just horizontally scrollable, we should ensure that this is preserved
- Document search on mobile: If we're going with the left column being a left-side drawer on mobile, perhaps when we search for documents, on click of the Result snippet, the drawer closes, and the normal ui interaction happens (scrolling document to corresponding text)

**Comment by longhotsummer** [comment]
Good write-up. Don't forget https://docs.google.com/document/d/1x-XNO2pTz46sZfKHP1TEWkqpU4JWdr35j8ObM1hngUo/edit# as a reference point where this layout is explored.

> First and foremost create a three-column grid UI for which akn, html and pdf document views use:

To re-phrase this, just so we're clear:

* the left column always exists; visible on desktop, fly-out on mobile. In all cases it contains in-document search. In cases where in-document navigation is supported (PDF, TOC), it also includes that. The business logic that renders the PDF preview or TOC shouldn't really care about whether it's being rendered in a sidebar at all -- it just puts the content into the correct place in the dom, which happens to be in the sidebar.

In other words, always prepare a three column layout and inject content into the correct places. As opposed to deciding on the type of layout for each type of document. The layout remains consistent, the content injected into the different parts changes.

> Thought needs to go into the color alignment used. i.e what background greys are we using

For PDF, don't render the background grey at all. I think that gives a better appearance that the page is a part of the current html page, rather than "embedded" (eg. see https://www.canlii.org/en/bc/bcca/doc/1951/1951canlii252/1951canlii252.html)

I'm tending towards the gutter also not having a background colour, particularly when it's empty (by far the common case).

> PDF pages are canvas elements with text layers overlaid on top of it. So the width of those pages must remain the same size, otherwise, text placement will not be correct if resized. Currently, on mobile view, the page is the same size, just horizontally scrollable, we should ensure that this is preserved

Ideally in no views should the rendered page overflow the viewport. So an idea is to check the width of the container where the pages will go and then render (at maximum?) into that width. Then we can configure the max-width of that container?

Resizing of the current viewport is (a) uncommon and (b) can be detected and the pages re-rendered.

**Comment by musangowope** [comment]
I agree with everything you have stated above.

Just one thought about this:
> Ideally in no views should the rendered page overflow the viewport. So an idea is to check the width of the container where the pages will go and then render (at maximum?) into that width. Then we can configure the max-width of that container?
> 
> Resizing of the current viewport is (a) uncommon and (b) can be detected and the pages re-rendered.

Yep, we can definitely render the page at the max width of the container. I'm just curious about how we're going to deal with rendering the page on a mobile-sized viewport. The page is going to be small and unreadable,😅  Something like this
<img width="463" alt="mobile-pdf" src="https://user-images.githubusercontent.com/15995210/175307519-fedf1e35-eb8b-42b6-8eb3-05e614422bae.png">
Hence adding a zoom feature would definitely be necessary

The value I see for a scrollable viewport is preserving readability🤔
