### ISSUE TITLE
As a search user, I would like to be able to filter by Judgment author in the general search

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#428]
as I search for terms across all content on the AGP platform. 

e.g. Currently, the search results list here: https://agp.africanlii.org/search/?q=%22food+security%22  does not filter by court - African Court, East African Court, etc.

![image](https://user-images.githubusercontent.com/46931873/190914682-1d79a0a0-cae2-48fb-9256-5e24f26e2871.png)

**Comment by longhotsummer** [comment]
This is related to https://github.com/laws-africa/peachjam/issues/429

**Comment by longhotsummer** [comment]
A key issue here is that our `Judgment` model has a FK to `Author`. I think that's a mistake and we should explicitly model judgment authors as a court -- 99% of judgments come from a court. That would mean that we can apply a common label to it in search, listings, etc.

**Comment by longhotsummer** [comment]
# Proposal

* create a new `Court` model
* add `court` as a FK from `Judgment` to `Court`
* migrate existing judgment data to use the new court
* drop author from the judgment model
* update import code to work with court rather than author for judgment documents
* add court field to search index
* add court facet to search

**Comment by longhotsummer** [comment]
@actlikewill what do you think about this proposal? Am I missing anything?

**Comment by actlikewill** [comment]
> @actlikewill what do you think about this proposal? Am I missing anything?

Sounds Good.
