### ISSUE TITLE
As a non-English user I need court names, taxonomy entries and other database-driven fields to be translated

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#642]
Model fields:

* [x] AttachedFileNature.name
* [x] Court.name
* [x] CourtClass.name
* [x] CourtRegistry.name
* [x] DocumentNature.name
* [x] OrderOutcome.name
* [x] Predicate.verb, Predicate.reverse_verb
* [x] Taxonomy.name

Related UI elements
* [ ] facet labels from Elasticsearch in /search

**Comment by longhotsummer** [comment]
Another option is https://django-modeltranslation.readthedocs.io/en/latest/installation.html which doesn't require changes to your models.

**Comment by longhotsummer** [comment]
@actlikewill pls can you do a deep dive and try out django-modeltranslations and see how it goes? If it goes well, then pls do a more thorough write-up on what needs to be changed/done, in particular for the search UI and the search backend, and how we handle migrating to using this setup.

**Comment by actlikewill** [comment]
@longhotsummer Sure.

**Comment by actlikewill** [comment]
The django-modeltranslations library is fairly simple and quick to use. Here is an outline of how we would use it.

### Config
- Pip install the library and add it to the installed apps. Be sure to add it above the admin site app in order to use it in  admin.
- Set the languages in the settings file. This is what the library will use to create the translations
- Add a translations.py file in peachjam and configure the transatlatble models  by: subclassing the TranslationOptions class, and adding the fields as below:
```
from modeltranslation.translator import translator, TranslationOptions, register
from peachjam.models import Court

@register(Court)
class CourtTranslationOptions(TranslationOptions):
    fields = ('name',)

```

- Run `python manage.py makemigrations`. It will create a migration file.
- It will add the translation fields to the model e.g for the above Court Model it will add `name_en`, `name_sw`, `name_fr` and `name_po` since those are the language options set on the peachjam settings file. 
- Take note that we need to add a backfill migration here to move the data from the old field to the new default field and probably the english one as well. (When I ran t `python manage.py migrate`  I lost the previous data I had, so this is important)

### Rendering
- Thankfully, there is nothing more to change in the views or the templates. It will pickup the application's current language and render the correct value :smiley_cat: 

### Search
- Adding the new translated fields to the SearchableDocument class and remapping the indexes will add them to the index

```
    court = fields.KeywordField(attr="court.name")
    court_en = fields.KeywordField(attr="court.name_en")
    court_sw = fields.KeywordField(attr="court.name_sw")
```

**Comment by actlikewill** [comment]
@longhotsummer I checked out django-modeltranslations and found the above. It works quite well and is not too much of a pain to setup. Django Parler would involve a fair bit of code change, even though it has more features.

**Comment by actlikewill** [comment]
Double check migrations for the above.

**Comment by actlikewill** [comment]
Manipulate the query that goes to elasticsearch to match users language.
