### ISSUE TITLE
Some static files links do not work on Pocketlaw

### ISSUE THREAD

**Issue by ro6ley** [laws-africa/peachjam#711]
PDFs on Pocketlaw while offline will not load due to how Django handles static files by adding hash values to the names, e.g. `https://lawlibrary.org.za/static/lib/pdfjs/pdf.worker.js` becomes `https://lawlibrary.org.za/static/lib/pdfjs/pdf.4a2a1c0fb5fb.js`  and the worker.js is not available in the archive produced by Wget.

Either we explicitly link to it in the HTML somewhere so wget picks it up, or we have to hardcode it as a URL into the wget request list.

See #668

**Comment by longhotsummer** [comment]
Solution:

1. on the site homepage, add a hidden link (ie. `display: none`) and no link text in the footer which links to `/pocketlaw-resources`
2. add a new page `/pocketlaw-resources`. This is intended only for use when we're using wget to scrap the site. The page will include the extra resources that wget otherwise doesn't know to fetch
3. on `/pocketlaw-resources`, it can be an empty page (base template), and add a script tag that explicitly loads `/static/lib/pdfjs/pdf.worker.js` (not using `{% static %}`!)


This means that wget will crawl the page and fetch `/static/lib/pdfjs/pdf.worker.js` which will then be available to pocketlaw.
