### ISSUE TITLE
As an advanced user of the AGP website, I'd like to access relevant Afrobarmeter content linked to AU documents

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#759]
AGP website editors should be able to manually link external documents to all AGP document content.

**Comment by NotoriousMBB** [comment]
This is a project deliverable for Yr2 of the project and should be prioritised before we go on leave.

**Comment by longhotsummer** [comment]
The idea here is we want to be able to link to an external URL from a document, as a relationship.

**Comment by longhotsummer** [comment]
This is the simplest implementation to get us going. We'll likely add more later as we work with Afrobarometer on this.

## Proposal

The idea is to add a new document type and model called ExternalDocument. We capture only enough information to identify the document and the work, but don't actually host the document at all. Instead, the `source_url` field is used to send the user to the actual remote document (or website).

This means that the document has a work and can participate in relationships.

* create a new ExternalDocument model which extends CoreDocument
  * use `doc_type = "external"`
  * use `frbr_uri_doctypes = ["doc"]`
* register a new document detail view for `ExternalDocument`. All this view does is redirect the user to `doc.source_url`
* in `peachjam_search.documents.SearchableDocument`, implement `should_index_object(self, obj)` and return `False` for documents that are instances of `ExternalDocument`, so that we don't index them for search

These documents

**Comment by longhotsummer** [comment]
We may in future want a background task to check for link rot, and highlight broken links to external sites so that editors can check and correct if necessary.
